name: x86_64 and i686 release builds

on:
  push:
    tags:
      - "*-rt_*-rev*"

jobs:
  split-tag:
    runs-on: ubuntu-latest
    outputs:
      gcc-version: ${{ steps.get-gcc-version.outputs.version }}
      rt-version: ${{ steps.get-rt-version.outputs.version }}
      mingw-rev: ${{ steps.get-mingw-revision.outputs.rev }}
    steps:
      - id: get-gcc-version
        run: echo "version=$(echo ${{ github.ref_name }} | cut -d- -f1)" >> $GITHUB_OUTPUT
      - id: get-rt-version
        run: echo "version=$(echo ${{ github.ref_name }} | cut -d- -f2 | cut -c4-)" >> $GITHUB_OUTPUT
      - id: get-mingw-revision
        run: echo "rev=$(echo ${{ github.ref_name }} | cut -d- -f3 | cut -c4-)" >> $GITHUB_OUTPUT

  build:
    needs: split-tag
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, i686]
        threads: [posix, win32, mcf]
        exceptions: [seh, dwarf]
        msvcrt: [msvcrt, ucrt]
        exclude:
          - arch: x86_64
            exceptions: dwarf
          - arch: i686
            exceptions: seh
          - threads: mcf
            msvcrt: msvcrt

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'niXman/mingw-builds'
        ref: 'develop'

    - uses: msys2/setup-msys2@v2
      with:
        update: true

    - name: Build
      shell: msys2 {0}
      run: >-
        ./build
        --mode=gcc-${{ needs.split-tag.outputs.gcc-version }}
        --buildroot=/c/buildroot
        --jobs=4
        --rev=${{ needs.split-tag.outputs.mingw-rev }}
        --with-default-msvcrt=${{ matrix.msvcrt }}
        --rt-version=${{ needs.split-tag.outputs.rt-version }}
        --threads=${{ matrix.threads }}
        --exceptions=${{ matrix.exceptions }}
        --arch=${{ matrix.arch }}
        --bin-compress
        --enable-languages=c,c++,fortran

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: 'archives'
        path: c:/buildroot/archives/

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: 'archives'
        path: ./

    - name: Upload to Release
      id: upload_to_release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.7z"
